### ISSUE TITLE
Speaker does not respon ARP requests

### ISSUE THREAD

**Issue by ananbas** [danderson/metallb#438] opened 2019-05-31 08:00 UTC
[BUG]: Speaker does not respon ARP request
     - Version of MetalLB : 0.7.3
     - Version of Kubernetes: 1.13.3
     - Network addon: WeaveNet 2.5.1
     - Kube-proxy using iptables

I got many services with different IPs:

Speaker not responded ARP to 10.30.225.3

```
[root@bdprden0003]# arping -I eno49 10.30.225.2
ARPING 10.30.225.2 from 10.30.225.37 eno49
Unicast reply from 10.30.225.2 [48:DF:37:00:FF:B8]  0.869ms
Unicast reply from 10.30.225.2 [48:DF:37:00:FF:B8]  0.755ms
Unicast reply from 10.30.225.2 [48:DF:37:00:FF:B8]  0.852ms
Unicast reply from 10.30.225.2 [48:DF:37:00:FF:B8]  0.797ms
^CSent 4 probes (1 broadcast(s))
Received 4 response(s)

[root@bdprden0003]# arping -I eno49 10.30.225.4
ARPING 10.30.225.4 from 10.30.225.37 eno49
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  1.117ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.899ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  1.219ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.861ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.924ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.856ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.811ms
^CSent 7 probes (1 broadcast(s))
Received 7 response(s)

[root@bdprden0003]# arping -I eno49 10.30.225.3
ARPING 10.30.225.3 from 10.30.225.37 eno49
^CSent 96 probes (96 broadcast(s))
Received 0 response(s)
```

```
~ $ kubectl get services --all-namespaces | grep 10.30.225.2
kube-cep      cep-api-deploy-http                        LoadBalancer   10.100.223.168   10.30.225.2   8100:30234/TCP                        21d
kube-cep      cep-api-uat-http                           LoadBalancer   10.107.40.58     10.30.225.2   8104:31615/TCP                        59d
kube-cep      cep-mysql-public                           LoadBalancer   10.105.168.255   10.30.225.2   3306:30524/TCP                        81d
kube-cep      cep-ui-http                                LoadBalancer   10.108.138.36    10.30.225.2   80:32289/TCP                          92d
kube-cep      cep-ui-ssh                                 LoadBalancer   10.96.184.145    10.30.225.2   9022:31580/TCP                        87d
kube-cep      cep-ui-uat-http                            LoadBalancer   10.109.155.118   10.30.225.2   8004:32356/TCP                        79d

~ $ kubectl get services --all-namespaces | grep 10.30.225.3
kong          kong-admin                                 LoadBalancer   10.98.22.247     10.30.225.3   8001:30911/TCP                        88d
kong          kong-proxy                                 LoadBalancer   10.104.102.126   10.30.225.3   8000:30896/TCP                        88d
kong          konga-web-public                           LoadBalancer   10.107.108.97    10.30.225.3   1337:30890/TCP                        86d
kube-db       postgres96-public                          LoadBalancer   10.104.71.180    10.30.225.3   5432:31599/TCP                        90d
prometheus    grafana                                    LoadBalancer   10.97.59.67      10.30.225.3   3000:32451/TCP                        86d
zabbix        zabbix-web-public                          LoadBalancer   10.103.114.17    10.30.225.3   8080:30779/TCP                        86d

~ $ kubectl get services --all-namespaces | grep 10.30.225.4
cdh-prod      pg96-cdh-prod-public                       LoadBalancer   10.105.231.194   10.30.225.4   5432:32571/TCP                        57d
```
Any help?

**Comment by ananbas** [comment] 2019-05-31 08:13
update: I need to kill the speaker pod in the node. then ARP request got replied.

do I need a cron to kill the speaker pod every week or so?

**Comment by ananbas** [comment] 2019-05-31 08:31
update:

killing speaker od is not solving problem, now it is from different machine:

```
[root@bdanlmn0002 ~]$ arping -I nm-bond 10.30.225.3
ARPING 10.30.225.3 from 10.30.225.146 nm-bond
^CSent 11 probes (11 broadcast(s))
Received 0 response(s)

[root@bdanlmn0002 ~]$ arping -I nm-bond 10.30.225.4
ARPING 10.30.225.4 from 10.30.225.146 nm-bond
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.813ms
Unicast reply from 10.30.225.4 [48:DF:37:00:FF:B8]  0.855ms
^CSent 2 probes (1 broadcast(s))
Received 2 response(s)
```

**Comment by aleks-mariusz** [comment] 2019-06-21 16:31
i have seen this problem as well on my lab cluster. it's quite annoying.. have you tried setting `externalTrafficPolicy` to `Local` ?   I was told this should fix it.. but this problem seems intermittent enough that reproducing it is a bit difficult to figure out if this change will keep it from happening.. 

FWIW, I'm specifically (and initially) relying heavily on metallb to build a custom on-prem kubernetes cluster which exposes an in-cluster powerdns deployment (that is controlled by externaldns), that then hosts a sub-domain I can delegate from my (internal) corporate domain (so through recursive queries at the top-level can find cluster-internal servers simply by a static/stable address).  Well DNS is pretty critical so i don't feel very comfortable relying on metallb if it randomly causes DNS to break due to this issue :-/

**Comment by Queuecumber** [comment] 2019-06-21 20:44
I'm also having this issue, it only happens on one of my nodes and for one of my services. I can't see any obvious difference between the working services and the one that doesnt work, but killing the speaker each time it happens reliably fixes it until the pod is restarted.

**Comment by aleks-mariusz** [comment] 2019-06-24 13:34
Might be related to https://github.com/danderson/metallb/issues/402 .. it's "fixed" but there's been no new releases since last summer so per [this comment](https://github.com/danderson/metallb/issues/399#issuecomment-468481117) the only way to get this in use is to use the [master branch's tag](https://hub.docker.com/r/metallb/speaker/tags) from 4 months ago :-/

**Comment by Queuecumber** [comment] 2019-06-24 13:37
Ooof last summer? @danderson when are you planning another release? @aleks-mariusz thanks for the heads up I'll switch over to the master tag and see if it resolves anything

**Comment by aleks-mariusz** [comment] 2019-06-24 13:41
my understanding is that @danderson no longer is able to commit the amount of time to this project as he used to, due to life circumstances.. which sounds unfortunately but that happens sometimes.. and any trickle of dev effort's are mainly focus setting up proper CI environment to not have the issues with new releases breaking things as was experienced with 0.7 coming out.. can't remember which github issue i read about this

but in any case, i've also pestered the #metallb channel on the kubernetes slack and hopefully someone there also has the ability to cut a release ?

**Comment by Queuecumber** [comment] 2019-06-24 13:43
Commit history is still pretty active, maybe its time for a co-maintainer to be appointed?

**Comment by danderson** [comment] 2019-06-24 16:22
@aleks-mariusz is correct. My job focus has shifted away from kubernetes. Separately, the state of testing on Kubernetes is so terrible that any development I do on MetalLB results in multiplied workload from bugs and complaints. These two factors combined mean I'm not really excited to spend time working on this for free :)

I'll try to get a release done some time this week, and I'll also use the opportunity to downgrade the stability and support promise, so that it's more clear that this is an unmaintained project.

**Comment by aleks-mariusz** [comment] 2019-06-24 17:25
personally i think it'll seem a bit alarming to newcomers of the project if it is deemed/discovered as an unmaintained project.. the beta stability status currently seems quite fair/adequate, downgrading from that would mean you're asking people to consider it alpha, which i feel will seriously limit the uptake of new users (perhaps that's the intent though).. perhaps have a meeting about electing a new co-maintainer or consider handing off the maintainer baton to the next generation of kubernetes developers? disclaimer: i wish i had the programming prowess you golang developers have but i can't consider myself a reasonable candidate for such a position

**Comment by Queuecumber** [comment] 2019-06-24 17:30
I agree the thing had been rock solid up until this issue, and I'm not sure what more features you'd want to add to it but I don't know the full story. I'd volunteer to help but I've never worked on the project before and I bet there is someone who contributed a lot that would do a better job. Also in terms of importance, as far as I know metallb is the only solution for people who don't run on a cloud environment so I consider this a critical piece of the ecosystem. Have you considered applying to the kubernetes incubator?

**Comment by danderson** [comment] 2019-06-24 17:30
The problem is not really elections or governance, it's finding someone who (a) wants the job of debugging the world's bare metal k8s clusters, (b) has the skills to do it, (c) won't insert malware into the code and distribute it with my name on it.

And yes, the point of downgrading to alpha is to be honest to users about what to expect. Kubernetes is a space that's full of companies trying to sell freemium services, so the default expectation is a level of support I am unwilling to provide in my free time. Since I can't fix the amount of support I can provide, the next best thing is to be honest about what to expect :(

**Comment by danderson** [comment] 2019-06-24 17:32
@Queuecumber What do you expect k8s incubation to help with? From my perspective, it's going to add more bureaucracy and paperwork, and still expect me to do all the work. Incubating doesn't magically attract developers afaict.

**Comment by Queuecumber** [comment] 2019-06-24 17:35
Man you've gotten quite a negative view of kubernetes. I have no idea how it works I just know its a route to getting it into officially supported repositories in which case they have to do something if you drop off the planet and stop developing it. Honestly I'm surprised you dont have more help since I think the kubernetes project itself was the one recommending people use this

**Comment by danderson** [comment] 2019-06-24 17:41
My view of Kubernetes is informed by a couple years of working on GKE as my day job. Yes, it's quite a negative view, which might explain why I don't work in that space any more ;)

My view is that incubation can help projects that either need governance because they're mostly owned by 1 company and the company wants to divest itself, or because the project needs technical resources (continuous builds, cloud resources...). It specifically does _not_ provide developers or technical expertise.

So, from my perspective, there would be a bunch of paperwork to propose the project for incubation, debate it, then do a bunch more paperwork for onboarding... And the net result would be that MetalLB has _way_ more visibility (== more users), and still only me as maintainer. If anything, I want less visibility at this point :(

**Comment by Queuecumber** [comment] 2019-06-24 17:44
Well like I said it's rock solid, so maybe it's not such a death sentence to put it up as pre-alpha expect zero support and go into PR merge only mode with an occasional release. 

BTW how did it come about that google owns the metallb copyright but otherwise has no affiliation with the project?

**Comment by danderson** [comment] 2019-06-24 17:52
I used to work at Google, and their opinion is that they own everything you create while you're an employee. There are ways around that, but for open source software the simplest/lowest effort option was to open-source the code and let Google keep the copyright.

So, basically, "stupid legal reasons + laziness" :)

**Comment by aleks-mariusz** [comment] 2019-06-25 12:31
really enjoyed the back story of mr anderson's experience with this project, however i have given the master branch a try to resolve the speaker stopping responding, and instead see now that my speaker pods won't stay up more than 15-20 minutes, they repeatedly die at regular intervals, and the pods eventually go into `CrashLoopBackOff` state.. i checked the log files but there's nothing at the end of the log files that would indicate why it's died.. any idea how i can go about debugging this? :-/ (or has anyone else w/ testing the 'master' branch's 'master' image tag also ran into this?)

**Comment by Queuecumber** [comment] 2019-06-25 12:40
Well I guess that backfired. One I try when stuff fails that sometimes gives more information is overriding the command with something like `sleep 1000` and the execing into the pod and running the intended command in a shell, maybe after installing GDB or whatever Go uses for debugging

**Comment by danderson** [comment] 2019-06-25 15:59
Dying with no logs sounds like either exceeding memory limits, or triggering a violation of one of the sandbox settings. I'd start by turning off those settings in the speaker DaemonSet to see if that stabilizes the pod. If it does, then you need A/B testing to figure out the culprit.

**Comment by aleks-mariusz** [comment] 2019-06-25 18:40
i would imagine if it ran into a memory limit,  it'd have something listed in the events for the namespace with the speakers.. i have no such events.. 
as for triggering a violation, i'm not sure how to turn off that kind of settings? i tried to exec into the pod to see if there was a --help output but it only accepts `--config` and `--node-name` params, and nothing in the configmap that seem it would be a useful debugging testing.. 
it seems to die after ~10 minutes with no recent messages in the log file at all really

**Comment by trevex** [comment] 2019-07-05 09:33
@aleks-mariusz you might be running into https://github.com/danderson/metallb/issues/427

@danderson as this issue got off topic anyway: MetalLB is a great project and the only viable solution for a lot of bare-metal clusters including my own :) 
The situation reminds me of when Mike Pall wanted to pull out of luajit development. A lot of companies relied on luajit so they changed to a governance model where Mike Pall had a temporary advisory role to help onboard new engineers.
Maybe there is a similar opportunity here where a simple governance model of shared responsibility could help you reduce your involvement and you might be able to fully dedicate your time to other endeavors after a temporary advisory role.
I personally think while it is a lot of paper work transitioning to CNCF governance for companies it makes it easier for companies to dedicate resources to a project.
However there is also the third option: A community-supported fork to give you a clean cut, but even there your backing of this option would probably be vital to make a successful transition.

**Comment by aleks-mariusz** [comment] 2019-07-08 16:26
> @aleks-mariusz you might be running into #427 

Spot on.. i updated that issue with some work-around patch commands as well, good spot!

**Comment by danderson** [comment] 2019-07-08 16:36
Cool, I'll close this as a duplicate and remove the read-only rootfs security config for now, while I figure out how to get rid of glog.

Duplicate of #427

**Closed by danderson** 2019-07-08 16:36 UTC
