### ISSUE TITLE
Outdated tutorial

### ISSUE THREAD

**Issue by e-minguez** [danderson/metallb#443] opened 2019-07-03 11:04 UTC
# The bug itself, as detailed as you can.
The minikube tutorial site doesn't seem to reflect the content of the repo.

For instance, the [tutorial](https://metallb.universe.tf/tutorial/minikube/#configure-metallb) says `kubectl logs -n metallb-system -l app=speaker` and the [repo](https://github.com/danderson/metallb/blob/master/website/content/tutorial/minikube.md#configure-metallb) says `kubectl logs -n metallb-system -l app=metallb,component=speaker`

**Comment by danderson** [comment] 2019-07-08 16:42
The website only updates when I repoint the `live-website` tag in the repository. Usually I only do this when a new release happens, because I want the docs in sync with the latest release, not the tip of the repo.

So, this is "working as intended", and will be fixed when I make a new MetalLB release (working on cleaning stuff up for that right now).

**Closed by danderson** 2019-07-08 16:42 UTC
