### ISSUE TITLE
ARP/NDP not work correctly on machines with multiple interfaces

### ISSUE THREAD

**Issue by icefed** [danderson/metallb#465] opened 2019-08-07 09:11 UTC
#### Problem
I have three servers and each has two interfaces for Internal & External network (different subnets), MetalLB speaker reply on the wrong interface when it received ExternalIP ARP request from Internal network interface, it cause my client(External network) can not reach ExternalIP.

#### What I want
MetalLB speaker should only reply when senderIP in interface‘s subnet.

Related to https://github.com/danderson/metallb/issues/165

**Comment by danderson** [comment] 2019-10-06 21:50
Duplicate of #277

**Closed by danderson** 2019-10-06 21:50 UTC

**Comment by icefed** [comment] 2019-10-08 01:51
@danderson Please read this issue's content, it's not the same.

**Comment by danderson** [comment] 2019-10-08 02:05
MetalLB replies on the interface where it receives the request. If you're seeing replies coming from the wrong interface, it means the ARP request is being delivered to (at least) the wrong interface. This is due to either a network topology issue (e.g. both your subnets are actually sharing an ethernet segment, rather than being separate VLANs), or to the problem described in the linked issue, where composite linux interfaces can cause spurious receives on the wrong interface.

The fix you suggest won't work, because listening on an interface that has no addresses assigned is a valid configuration that's being used by other deployments.

**Comment by icefed** [comment] 2019-10-08 03:38
I think you misunderstand.
I have two interfaces which have different subnet 192.168.10.x and 192.168.20.x, connect to one switch, so maybe this is a network topology issue, but it should work.

my fix is not `listening all interfaces alse contains that has no addresses assigned `, but just implemented your design: https://github.com/danderson/metallb/issues/165
> 
> What you expected to happen:

> The ARP speaker should just listen for ARP traffic on all interfaces, and respond to relevant queries on the correct interface (i.e. the interface that has an address/cidr compatible with the requested IP).

> So, then, each goroutine just needs to do the same readPacket loop that already exists, but additionally needs to check if the IP in the ARP request is contained within the configured subnet for the current interface (e.g. "is 10.1.2.3 in 10.1.2.0/24 ? Yes, that means I should respond").

I don't know why you not code it, I fixed it (https://github.com/icefed/metallb/commit/f8270d6e1aebe305b1d68e5cd57b87fe6adf899b) and working good in my environment, also solved my problem.
